### ISSUE TITLE
Make cdn resistant to git reset

### ISSUE THREAD

**Issue by geophree** [tes/bosco#123]
When @dbellizzi does a `git reset --hard` that changes directories around, `bosco cdn` blows up with:
```
13:39 $ /Users/dbellizzi/.nvm/versions/v4.2.3/lib/node_modules/bosco/commands/cdn.js:103
      return f.match(watchRegex) && stat.isDirectory() || watchSet[f];
                                        ^
TypeError: Cannot read property 'isDirectory' of undefined
    at Object.filterFn [as filter] (/Users/dbellizzi/.nvm/versions/v4.2.3/lib/node_modules/bosco/commands/cdn.js:103:41)
    at /Users/dbellizzi/.nvm/versions/v4.2.3/lib/node_modules/bosco/node_modules/watch/main.js:87:50
    at FSReqWrap.oncomplete (fs.js:82:15)
[1]+  Exit 1                  bosco cdn -w app-resource
```

**Comment by cliftonc** [comment]
@geophree @dbellizzi does this still happen with the changes above?

**Comment by geophree** [comment]
I think this should be fine now that bosco doesn't watch.
