### ISSUE TITLE
Test failures on node 4.2.6

### ISSUE THREAD

**Issue by geophree** [tes/bosco#129]
They look to be related to my bosco dir migration code.

From @cliftonc:
Some of the 'bosco' tests don't pass - but no idea what they do - @geophree ?
```
1) bosco config folder should default to dot-dir for config on not-linux:
     Error: expected '/Users/ccunningham/.bosco' to equal '/my/home/.bosco'
      at Assertion.assert (node_modules/expect.js/index.js:96:13)
      at Assertion.be.Assertion.equal (node_modules/expect.js/index.js:216:10)
      at Assertion.(anonymous function) [as be] (node_modules/expect.js/index.js:69:24)
      at Context.<anonymous> (test/bosco.test.js:72:68)

  2) bosco config folder should call migrate with correct args:
     ExpectationError: Unexpected call: _migrateConfig(/Users/ccunningham/.bosco, /my/home/.config/bosco)
    Expected _migrateConfig(/my/home/.bosco, /my/home/.config/bosco[, ...]) once (never called)
      at Object.fail (node_modules/sinon/lib/sinon/mock.js:449:33)
      at Object.invokeMethod (node_modules/sinon/lib/sinon/mock.js:181:35)
      at Bosco._migrateConfig (node_modules/sinon/lib/sinon/mock.js:89:43)
      at Bosco.findConfigFolder (index.js:9:18730)
      at getConfigDir (test/bosco.test.js:39:22)
      at Context.<anonymous> (test/bosco.test.js:79:7)

  3) bosco "after each" hook for "should call migrate with correct args":
     ExpectationError: Expected _migrateConfig(/my/home/.bosco, /my/home/.config/bosco[, ...]) once (never called)
      at Object.fail (node_modules/sinon/lib/sinon/mock.js:449:33)
      at Object.verify (node_modules/sinon/lib/sinon/mock.js:129:39)
      at each (node_modules/sinon/lib/sinon/collection.js:34:33)
      at Object.resolve [as verify] (node_modules/sinon/lib/sinon/collection.js:50:17)
      at Object.verifyAndRestore (node_modules/sinon/lib/sinon/collection.js:66:26)
      at Context.<anonymous> (test/bosco.test.js:22:26)
```

**Comment by geophree** [comment]
Looks like this is a node version issue.  Fine with `v0.10.38`, but breaks with `v4.2.6`.
