### ISSUE TITLE
In node 6.2.1

### ISSUE THREAD

**Issue by Fetz** [tes/bosco#152]
Error in [Node.js line 63](https://github.com/tes/bosco/blob/master/src/RunWrappers/Node.js#L63)

``` shell
/Users/<username>/.nvm/versions/node/v6.2.1/lib/node_modules/bosco/src/RunWrappers/Node.js:63
          interpreter = data.replace('\n', '');
                             ^

TypeError: data.replace is not a function
    at Socket.<anonymous> (/Users/lfetzner/.nvm/versions/node/v6.2.1/lib/node_modules/bosco/src/RunWrappers/Node.js:63:30)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at Pipe.onread (net.js:542:20)
```

**Comment by tomruttle** [comment]
I've raised a bug against node: https://github.com/nodejs/node/issues/7342

**Comment by gabceb** [comment]
It looks like this may be fixed for 6.x.x but the change will be back for 7.x.x so we may want to have code to deal with both situations (string vs object)

**Comment by MerlinDMC** [comment]
We have dependencies that require at least Node v6.5.0 so I'll close this.
