### ISSUE TITLE
Issue after upgrade from 0.5.45 to 0.5.46

### ISSUE THREAD

**Issue by Crispy1975** [tes/bosco#169]
After upgrading to `0.5.46` and running `bosco exec git checkout master` now results in the following error message being thrown.

```
/home/crispy/npm/lib/node_modules/bosco/node_modules/lodash/lodash.js:10485
        throw new TypeError(FUNC_ERROR_TEXT);
        ^

TypeError: Expected a function
    at Function.rest (/home/crispy/npm/lib/node_modules/bosco/node_modules/lodash/lodash.js:10485:15)
    at Object.cmd (/home/crispy/npm/lib/node_modules/bosco/commands/exec.js:13:19)
    at Bosco._cmd (/home/crispy/npm/lib/node_modules/bosco/index.js:246:19)
    at /home/crispy/npm/lib/node_modules/bosco/index.js:115:10
    at /home/crispy/npm/lib/node_modules/bosco/index.js:147:9
    at /home/crispy/npm/lib/node_modules/bosco/index.js:188:5
    at /home/crispy/npm/lib/node_modules/bosco/node_modules/async/lib/async.js:726:13
    at /home/crispy/npm/lib/node_modules/bosco/node_modules/async/lib/async.js:52:16
    at /home/crispy/npm/lib/node_modules/bosco/node_modules/async/lib/async.js:269:32
    at /home/crispy/npm/lib/node_modules/bosco/node_modules/async/lib/async.js:44:16
```

**Comment by cliftonc** [comment]
I'll take a look now.

**Comment by cliftonc** [comment]
Released with 0.5.47.

**Comment by Crispy1975** [comment]
@cliftonc checking locally now...

**Comment by Crispy1975** [comment]
Confirmed to be working now @cliftonc thanks for the quick turnaround. :+1:
