### ISSUE TITLE
Intermittent failures in tests

### ISSUE THREAD

**Issue by geophree** [tes/bosco#186]
```
  1) Bosco Static Asset Handling should not re-minify already minified assets:
     Uncaught Error: expected 'child-exit' to equal 'timeout'
      at Assertion.assert (node_modules/expect.js/index.js:96:13)
      at Assertion.be.Assertion.equal (node_modules/expect.js/index.js:216:10)
      at Assertion.(anonymous function) [as be] (node_modules/expect.js/index.js:69:24)
      at Object.options.watchCallback (test/ExternalBuild.test.js:193:33)
      at buildFinished (src/ExternalBuild.js:9:7200)
      at buildCompleted (src/ExternalBuilders/SpawnWatch.js:9:1869)
      at ChildProcess.onChildExit (src/ExternalBuilders/SpawnWatch.js:9:5005)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
```

It looks like it's related to the new build code.

**Comment by cliftonc** [comment]
I'll take a look today, have also seen this.

**Comment by cliftonc** [comment]
Haven't seen this recur post the time increase.
