### ISSUE TITLE
Bosco errors with an uninformative message when github token is not authorised

### ISSUE THREAD

**Issue by raoulmillais** [tes/bosco#240]
If you change your github API access token and invalidate your existing one without updating your bosco config then the github API responds with a 401 Unauthorised response.  The bosco error message is not very informative however and it's not obvious what went wrong.

```
/Users/raoulmillais/code/tes/bosco/node_modules/octonode/lib/octonode/client.js:204
        return callback(new HttpError(body.message, res.statusCode, res.headers, body));
               ^
TypeError: Cannot read property 'link' of undefined
    at /Users/raoulmillais/code/tes/bosco/commands/clone.js:28:57
    at Client.errorHandle (/Users/raoulmillais/code/tes/bosco/node_modules/octonode/lib/octonode/client.js:204:16)
    at Request._callback (/Users/raoulmillais/code/tes/bosco/node_modules/octonode/lib/octonode/client.js:220:24)
    at Request.self.callback (/Users/raoulmillais/code/tes/bosco/node_modules/request/request.js:186:22)
    at Request.emit (events.js:159:13)
    at Request.<anonymous> (/Users/raoulmillais/code/tes/bosco/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:159:13)
    at IncomingMessage.<anonymous> (/Users/raoulmillais/code/tes/bosco/node_modules/request/request.js:1085:12)
```

**Comment by raoulmillais** [comment]
This is not just for token revocation it also happens if DNS resolution fails.
