### ISSUE TITLE
bosco rabbit diff is broken

### ISSUE THREAD

**Issue by tomchambers2** [tes/bosco#56]
```
Toms-MacBook-Pro:files work$ bosco rabbit-diff staging-definitions.json live-definitions.json 
[04:09:19] Bosco: Why does it feel like I fell on my face?
[04:09:19] Bosco: Initialised using [/Users/work/resources/.bosco/bosco.json] in environment [local]

fs.js:438
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory './node_modules/jsondiffpatch/public/formatters-styles/html.css'
    at Object.fs.openSync (fs.js:438:18)
    at Object.fs.readFileSync (fs.js:289:15)
    at Object.cmd (/Users/work/resources/commands/rabbit-diff.js:46:22)
    at Bosco._cmd (/Users/work/.nvm/v0.10.33/lib/node_modules/bosco/index.js:240:44)
    at /Users/work/.nvm/v0.10.33/lib/node_modules/bosco/index.js:93:14
    at /Users/work/.nvm/v0.10.33/lib/node_modules/bosco/index.js:139:17
    at /Users/work/.nvm/v0.10.33/lib/node_modules/bosco/index.js:191:9
    at /Users/work/.nvm/v0.10.33/lib/node_modules/bosco/node_modules/async/lib/async.js:254:17
    at /Users/work/.nvm/v0.10.33/lib/node_modules/bosco/node_modules/async/lib/async.js:157:25
    at /Users/work/.nvm/v0.10.33/lib/node_modules/bosco/node_modules/async/lib/async.js:251:21
```

**Comment by cliftonc** [comment]
This module is in the resources project (it is a local command) - I'll close this and move it over there.
