### ISSUE TITLE
Docker 'build: true' needs to be in the project directory

### ISSUE THREAD

**Issue by cliftonc** [tes/bosco#83]
Most bosco commands are run from the root of the workspace (e.g. ```resources```).  If you run:

```
bosco run -r nginx
```

With nginx configured this way, it fails to build:

```
➜  404  bosco run -r nginx
[04:51:18] Bosco: Maybe he can't, but I can!
[04:51:18] Bosco: Initialised using [/Users/cliftonc/.bosco/bosco.json] in environment [local] with team [tes/404]
[04:51:18] Bosco: Run each microservice ... 
[04:51:18] Bosco: Removing stopped/dead services
[04:51:18] Bosco: Running docker service infra-nginx-gateway ...
[04:51:18] Bosco: Building image for infra-nginx-gateway ...
[04:52:24] Bosco: Error: HTTP code is 500 which indicates error: server error - Cannot build a directory without a Dockerfile

    at /Users/cliftonc/work/bosco/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:207:17
    at IncomingMessage.<anonymous> (/Users/cliftonc/work/bosco/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:232:9)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickDomainCallback (node.js:486:13)

/Users/cliftonc/work/bosco/src/RunWrappers/DockerUtils.js:174
        stream.on('data', function(data) {
               ^
TypeError: Cannot call method 'on' of null
    at /Users/cliftonc/work/bosco/src/RunWrappers/DockerUtils.js:174:16
    at /Users/cliftonc/work/bosco/node_modules/dockerode/lib/docker.js:147:5
    at /Users/cliftonc/work/bosco/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:213:7
    at IncomingMessage.<anonymous> (/Users/cliftonc/work/bosco/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:232:9)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickDomainCallback (node.js:486:13)
```

The reason appears to be that the Docker file is trying to build the image where bosco is being run, not where the project is.

**Comment by cliftonc** [comment]
Not sure how you do this by the way, but this looks promising:

https://github.com/apocas/dockerode/blob/master/examples/build/build_img_cwd.js#L8

**Comment by cliftonc** [comment]
Is the 'build' property supposed to be a template?

https://github.com/tes/bosco/blob/master/src/RunWrappers/DockerUtils.js#L164

**Comment by geophree** [comment]
Yeah, see https://github.com/tes/service-pdf/blob/master/bosco-service.json . It's a path, with `{PATH}` substituted for the repo directory.  So most of the time, it'll just be `"build": "{PATH}"`.  I should have realized it sooner, I haven't used that code much recently.

I think I made it that way because any Binds need to be full paths, and I wanted consistency between them.  We use a similar substitution in Cmds as well.  You may also want to base the docker build on a subdirectory.  We could change the build option to be a relative path that we then resolve based on the repo directory, but I don't see how to change the Cmd one easily.

**Comment by cliftonc** [comment]
Closing, as this was me not understanding how it worked.
